[pytest]
testpaths = tests
addopts = -q -p no:cacheprovider
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated:DeprecationWarning
    ignore:on_event is deprecated:DeprecationWarning
